name: checks

on:
  pull_request:
  push:
    branches: [main]

jobs:
  python:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: 1.94.0
          components: rustfmt, clippy
      - uses: astral-sh/setup-uv@v6
      - run: scripts/bootstrap
      - run: scripts/check
